# Generated by Django 3.1.2 on 2021-04-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='saldo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='saldo',
            field=models.PositiveIntegerField(null=True, verbose_name='Saldo disponible'),
        ),
    ]
