# Generated by Django 3.1.2 on 2021-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('rut_empresa', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut Empresa')),
                ('rsocial_empresa', models.CharField(max_length=30, verbose_name='Razon Social Empresa')),
                ('direccion_empresa', models.CharField(max_length=30, null=True, verbose_name='Direccion Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
    ]
