# Generated by Django 3.1.2 on 2021-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0002_auto_20210406_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='casino',
            fields=[
                ('rut_casino', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut Casino')),
                ('rsocial_casino', models.CharField(max_length=30, verbose_name='Razon Social Casino')),
                ('dir_casino', models.CharField(max_length=30, verbose_name='Direccion Casino')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
            },
        ),
        migrations.CreateModel(
            name='comedor',
            fields=[
                ('id_comedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_comedor', models.CharField(max_length=15, verbose_name='Nombre Comedor')),
            ],
            options={
                'verbose_name': 'Comedor',
                'verbose_name_plural': 'Comedores',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('cod_prod', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('nom_prod', models.CharField(max_length=15, verbose_name='Nombre Producto')),
                ('des_prod', models.CharField(max_length=30, null=True, verbose_name='Descripcion')),
                ('precio_prod', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sucursal', models.CharField(max_length=15, verbose_name='Nombre Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
    ]
