# Generated by Django 3.1.2 on 2021-04-24 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_auto_20210424_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe_ticket',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe_ticket',
            name='fecha_termino',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha termino'),
            preserve_default=False,
        ),
    ]
