# Generated by Django 3.1.2 on 2021-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_boleta_categoria_empleado_departamento_error_calc_tickets_forma_pago_informe_ticket_mensual_pedido_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=30, verbose_name='Nombre')),
                ('appaterno_emp', models.CharField(max_length=30, verbose_name='Apellido paterno')),
                ('apmaterno_emp', models.CharField(max_length=30, verbose_name='Apellido materno')),
                ('numrut_emp', models.IntegerField(max_length=10, verbose_name='rut Empleado sin guion')),
                ('dvrut_emp', models.CharField(max_length=1, verbose_name='Numero verificador')),
                ('direccion_emp', models.CharField(max_length=30, verbose_name='Direccion Empleado')),
                ('email_emp', models.EmailField(max_length=30, verbose_name='Email Empleado')),
                ('tel_emp', models.IntegerField(max_length=9, verbose_name='Numero Empleado')),
                ('sueldo_emp', models.IntegerField(max_length=7, verbose_name='Sueldo Empleado')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('password_emp', models.CharField(max_length=10, verbose_name='Contraseña Empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='empleado_casino',
            fields=[
                ('id_emp_casino', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp_casino', models.CharField(max_length=30, verbose_name='Nombre')),
                ('appat_emp_casino', models.CharField(max_length=30, verbose_name='Apellido paterno')),
                ('apmat_emp_casino', models.CharField(max_length=30, verbose_name='Apellido materno')),
                ('rut_emp_casino', models.IntegerField(max_length=10, verbose_name='rut Empleado sin guion')),
                ('dv_rut_emp_casino', models.CharField(max_length=1, verbose_name='Numero verificador')),
                ('tel_emp_casino', models.IntegerField(max_length=9, verbose_name='Numero Empleado')),
                ('password_emp_casino', models.CharField(max_length=10, verbose_name='Contraseña Empleado')),
            ],
            options={
                'verbose_name': 'Empleado Casino',
                'verbose_name_plural': 'Casino Empleados',
            },
        ),
    ]
