# Generated by Django 3.1.2 on 2021-04-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_auto_20210424_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='email empleado'),
        ),
    ]
