# Generated by Django 3.1.2 on 2021-04-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0005_empleado_empleado_casino'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fk_pedido_casino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.pedido_casino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='fk_ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='fk_sucursal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comedor',
            name='fk_casino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.casino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_categoria_empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.categoria_empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_comuna',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_tipo_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.tipo_usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.turno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado_casino',
            name='fk_comedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.comedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado_casino',
            name='fk_comuna',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='fk_comuna',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fk_empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='saldo_por_pagar',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo por Pagar'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='valor_ticket',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Ticket'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numrut_emp',
            field=models.IntegerField(verbose_name='rut Empleado sin guion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='password_emp',
            field=models.CharField(max_length=50, verbose_name='Contraseña Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_emp',
            field=models.IntegerField(verbose_name='Sueldo Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tel_emp',
            field=models.IntegerField(verbose_name='Numero Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado_casino',
            name='rut_emp_casino',
            field=models.IntegerField(verbose_name='rut Empleado sin guion'),
        ),
        migrations.AlterField(
            model_name='empleado_casino',
            name='tel_emp_casino',
            field=models.IntegerField(verbose_name='Numero Empleado'),
        ),
        migrations.AlterField(
            model_name='informe_ticket_mensual',
            name='cant_boletas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_ticket_mensual',
            name='cant_tickets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_ticket_mensual',
            name='total_boletas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_ticket_mensual',
            name='total_tickets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_ticket_mensual',
            name='total_ventas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_prod',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterModelTable(
            name='boleta',
            table='BOLETA',
        ),
        migrations.AlterModelTable(
            name='casino',
            table='CASINO',
        ),
        migrations.AlterModelTable(
            name='categoria_empleado',
            table='CATEGORIA_EMPLEADO',
        ),
        migrations.AlterModelTable(
            name='comedor',
            table='COMEDOR',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='COMUNA',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='DEPARTAMENTO',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='EMPLEADO',
        ),
        migrations.AlterModelTable(
            name='empleado_casino',
            table='EMP_CASINO',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='EMPRESA',
        ),
        migrations.AlterModelTable(
            name='error_calc_tickets',
            table='ERROR_CALC_TICKET',
        ),
        migrations.AlterModelTable(
            name='forma_pago',
            table='FORMA_PAGO',
        ),
        migrations.AlterModelTable(
            name='informe_ticket_mensual',
            table='INFORME_TICKET_MENSUAL',
        ),
        migrations.AlterModelTable(
            name='pedido_casino',
            table='PEDIDO_CASINO',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='PRODUCTO',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='SUCURSAL',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='TICKET',
        ),
        migrations.AlterModelTable(
            name='tipo_usuario',
            table='TIPO_USUARIO',
        ),
        migrations.AlterModelTable(
            name='turno',
            table='TURNO',
        ),
        migrations.CreateModel(
            name='tickets_empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.empleado')),
                ('fk_ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CORE.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='producto_comedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fk_comedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.comedor')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto')),
            ],
            options={
                'verbose_name': 'Inventario comedor',
                'verbose_name_plural': 'Inventario comedores',
                'db_table': 'PRODUCTOS_COMEDOR',
            },
        ),
        migrations.CreateModel(
            name='pedido_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fk_pedido_casino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.pedido_casino')),
                ('fk_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto')),
            ],
            options={
                'verbose_name': 'pedido de producto',
                'verbose_name_plural': 'pedido  de productos',
                'db_table': 'PEDIDO_PRODUCTOS',
            },
        ),
    ]
