# Generated by Django 3.1.2 on 2021-04-27 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0005_empleado_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE_BOLETA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('fk_codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto')),
            ],
            options={
                'verbose_name': 'detalle boleta',
                'verbose_name_plural': 'detalles boletas',
                'db_table': 'DETALLE_BOLETA',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='hora_venta',
            field=models.CharField(default='a', max_length=5, verbose_name='hora venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe_ticket',
            name='tipo_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='CORE.tipo_producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fk_codigo_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CORE.ticket'),
        ),
        migrations.DeleteModel(
            name='DETALLE_TICKET',
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='fk_num_boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.boleta'),
        ),
    ]
