# Generated by Django 3.1.2 on 2021-04-27 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0006_auto_20210426_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEDIDO_TICKET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('fk_codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto')),
                ('fk_num_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.ticket')),
            ],
            options={
                'verbose_name': 'pedido ticket',
                'verbose_name_plural': 'pedidos tickets',
                'db_table': 'PEDIDO TICKET',
            },
        ),
    ]
