# Generated by Django 3.1.2 on 2021-04-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0006_auto_20210410_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets_usados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.empleado')),
                ('fk_ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CORE.ticket')),
                ('fk_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.turno')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='fk_forma_pago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.forma_pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado_casino',
            name='password_emp_casino',
            field=models.CharField(max_length=50, verbose_name='Contraseña Empleado'),
        ),
        migrations.AlterField(
            model_name='producto_comedor',
            name='fk_producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto'),
        ),
        migrations.DeleteModel(
            name='tickets_empleados',
        ),
    ]
