# Generated by Django 3.1.2 on 2021-04-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0007_pedido_ticket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido_ticket',
            table='PEDIDO_TICKET',
        ),
    ]
