# Generated by Django 3.1.2 on 2021-04-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0007_auto_20210411_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets_usados',
            options={'verbose_name': 'ticket usado', 'verbose_name_plural': 'tickets usados'},
        ),
        migrations.AlterModelTable(
            name='tickets_usados',
            table='tickets_usados',
        ),
    ]
