# Generated by Django 3.1.2 on 2021-04-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0008_auto_20210426_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_ticket',
            name='tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CORE.tipo_producto'),
        ),
    ]
