# Generated by Django 3.1.2 on 2021-04-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0009_auto_20210411_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_producto',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto_comedor'),
        ),
    ]
