# Generated by Django 3.1.2 on 2021-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0010_auto_20210411_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valor',
            field=models.PositiveIntegerField(default=0, verbose_name='valor ticket'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_prod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
