# Generated by Django 3.1.2 on 2021-04-12 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0013_auto_20210411_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_producto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_producto', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'tipo producto',
                'verbose_name_plural': 'tipo de productos',
                'db_table': 'TIPO_PRODUCTO',
            },
        ),
        migrations.AddField(
            model_name='error_calc_tickets',
            name='fecha_error',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_tipo_producto',
            field=models.IntegerField(default=0, verbose_name='numero'),
            preserve_default=False,
        ),
    ]
