# Generated by Django 3.1.2 on 2021-04-12 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0014_auto_20210412_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fk_tipo_producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CORE.tipo_producto'),
        ),
    ]
