# Generated by Django 3.1.2 on 2021-04-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0016_auto_20210412_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_empleado',
            options={'verbose_name': 'Categoria Empleado', 'verbose_name_plural': 'Categorias de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empleado_casino',
            options={'verbose_name': 'Empleado Casino', 'verbose_name_plural': 'Empleados de Casinos'},
        ),
    ]
