# Generated by Django 3.1.2 on 2021-04-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0017_auto_20210412_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_comedor',
            name='fk_comedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.comedor'),
        ),
        migrations.AlterField(
            model_name='producto_comedor',
            name='fk_producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto'),
        ),
    ]
