# Generated by Django 3.1.2 on 2021-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0018_auto_20210418_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nombreUsuario',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
    ]
