# Generated by Django 3.1.4 on 2021-04-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0019_empleado_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_comedor',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CORE.producto'),
        ),
    ]
