# Generated by Django 3.1.2 on 2021-04-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0021_auto_20210421_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPRESA',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=30, verbose_name='nombre empresa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='SUCURSAL',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50, verbose_name='nombre sucursal')),
                ('direccion_sucursal', models.CharField(max_length=150, verbose_name='direccion sucursal')),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'SUCURSAL',
            },
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fk_comuna',
        ),
        migrations.DeleteModel(
            name='COMUNA',
        ),
        migrations.AddField(
            model_name='cajero',
            name='fk_sucursal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='CORE.empresa'),
            preserve_default=False,
        ),
    ]
