# Generated by Django 3.1.2 on 2021-04-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0022_auto_20210421_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='habilitado'),
        ),
    ]
